### ISSUE TITLE
Esqueleto de contenidos

### ISSUE THREAD

**Issue by normaars** [caixamagica/participacao#11]

**Comment by ricardopoppi** [comment]
@normaars podes incluir em enlace del doc aqui?

**Comment by ricardopoppi** [comment]
https://docs.google.com/document/d/1gmZoouYqR6ukTF7rrGOtsQSrbRCOFXW3tQgsWCfsR44/edit?usp=sharing

**Comment by ricardopoppi** [comment]
estamos trabajando este documento em la tarefa del pitch
