### ISSUE TITLE
Nuestro diario

### ISSUE THREAD

**Issue by marielzasso** [caixamagica/participacao#2]
Dia 1. Se conhecendo melhor e tentando descobrir "Que es participación ciudadana" para nosotros.
![uploads/245c5a5a-9409-410f-a27a-7ede2027e661/caixa_magica.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F245c5a5a-9409-410f-a27a-7ede2027e661%2Fcaixa_magica.jpg)

**Comment by marielzasso** [comment]
Dia 2: Ana comparte informacióin sobre diseño participativo. Norma habla de grados de participación. ![apvxvqrlan4vqjelninxjfh8i5mrixtjhfkkmrsyib-8](https://cloud.githubusercontent.com/assets/15890334/11214164/e062eabe-8d26-11e5-9ddb-c7359055dd9a.jpg)
![aiz9r-26k5vc1wiupbd6j6ucurtkdezwxlanvcxmnjyg 1](https://cloud.githubusercontent.com/assets/15890334/11214167/e07356b0-8d26-11e5-9a54-f474b3a4e611.jpg)

**Comment by marielzasso** [comment]
![ai5orvb-f9anr91jvmd1fcszn_9llefpz-qhgfcfpu7_](https://cloud.githubusercontent.com/assets/15890334/11214234/3c399df6-8d27-11e5-9672-6cb9d95aa073.jpg)

**Comment by marcoamarelo** [comment]
@marielzasso acho legal usarmos o Wiki do projeto para organizar isso, o que acha?

**Comment by marielzasso** [comment]
Cual es la wiki do projeto?

**Comment by marcoamarelo** [comment]
Acá https://github.com/caixamagica/participacao/wiki/Caja-M%C3%A1gica---Caixa-M%C3%A1gica

**Comment by marcoamarelo** [comment]
Hay que mejorar :-)

**Comment by marcoamarelo** [comment]
Poderíamos migrar também o conteúdo que colocamos no PAD para dentro do Wiki @marielzasso

**Comment by marielzasso** [comment]
Ok!

**Comment by ricardopoppi** [comment]
criando tarefa pra migração do pad, fechando essa issue pois toda documentação do projeto está no readme
